url: https://tirelesswake.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Tireless Wake
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 801515
  secondary: D46A6A
  secondary-dark: 204060

# Team names, titles and social links
people:
- name: Jim Howk
  pic: 1
  position: Technical Lead
  social:
    - title: twitter
      url: https://twitter.com/howkj1
    - title: linkedin
      url: https://www.linkedin.com/in/jimhowk
    - title: github
      url: https://github.com/tirelesswake

- name: Josh McCall
  pic: 2
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Sarah Howk
  pic: 3
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 1035 68th Street
  - line: West Des Moines, IA 50266

# Build settings
markdown: kramdown
permalink: pretty
